#!/bin/sh
#
# Startup script for the ha-agent daemon
#
# processname: ha-agent
# pidfile: /var/run/ha-agent.pid
# config: 
# chkconfig: 345 25 75
# description: Start and stop ha-agent

# Global definitions
ha_agent='/usr/cloudos/slb/sbin/ha-agent'
ha_agent_lock="/var/lock/subsys/ha-agent"

# source function library
. /etc/init.d/functions
ulimit -S -c unlimited

RETVAL=0

watchdog_remove() {
    local service tmp
    service=$1
    `cat /usr/cloudos/slb/watchsvc.conf  |grep -v $service > /tmp/watchsvc`
    cp -rf /tmp/watchsvc  /usr/cloudos/slb/watchsvc.conf
}

watchdog_add() {
    local service tmp
    service=$1
    `cat /usr/cloudos/slb/watchsvc.conf  |grep -v $service > /tmp/watchsvc`
    echo $service >> /tmp/watchsvc
    cp -rf /tmp/watchsvc  /usr/cloudos/slb/watchsvc.conf
}

start() {
    echo -n "Starting ha-agent: "
    if [ -f ${ha_agent_lock} ]; then
        echo ha-agent already running
        RETVAL=0
    else
        DAEMON_COREFILE_LIMIT=unlimited daemon $ha_agent
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch ${ha_agent_lock}
    fi

    watchdog_add ha-agent
}

stop() {
    watchdog_remove ha-agent
    echo -n "Shutting down ha-agent: "
    killproc $ha_agent
    echo
    RETVAL=0
    [ $RETVAL -eq 0 ] && rm -f ${ha_agent_lock}
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  status)
        status $ha_agent
        RETVAL=$?
        ;;
  condrestart)
        [ -f ${ha_agent_lock} ] && $0 restart || :
        ;;
  *)
	echo "Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac

exit $RETVAL
