/*
 *              COPYRIGHT (c) 2009-2015  CCMA 
 *                     ALL RIGHTS RESERVED 
 *
 * Description: IPC message type of slb_communicator.c
 * Filename:    slb_communicator_message_type.h
 * Author:      Vernon Sung, <vernonsung@itri.org.tw>
 *
 */

#ifndef _SLB_COMMUNICATOR_MESSAGE_TYPE_H
#define _SLB_COMMUNICATOR_MESSAGE_TYPE_H

#define SLB_COMMUNICATOR_PATH "slb"  // IPC ID

// Message types
enum SLB_COMMUNICATOR_MESSAGE_TYPE {
    SLB_COMMUNICATOR_MESSAGE_TYPE_FIRST = 0,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVcUuidByVmUuid,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVcUuidByVmUuid_REPLY,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getCnIpByVmUuid,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getCnIpByVmUuid_REPLY,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getSlbIpByVmUuid,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getSlbIpByVmUuid_REPLY,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVmIpByVmUuid,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVmIpByVmUuid_REPLY,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVcIpByVmUuid,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVcIpByVmUuid_REPLY,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getSlbIpByVcUuid,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getSlbIpByVcUuid_REPLY,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVcIpByVcUuid,
    SLB_COMMUNICATOR_MESSAGE_TYPE_getVcIpByVcUuid_REPLY,
    SLB_COMMUNICATOR_MESSAGE_TYPE_LAST
};

#endif
